### ISSUE TITLE
EU long term dataset

### ISSUE THREAD

**Issue by grdiv** [xingyuuchen/LIO-PPF#1]
Hello, I saw that the [1] dataset was used in the paper, but I can't download it from the official channel now, can you share it?
[1] Z. Yan, L. Sun, T. Krajnik, and Y. Ruichek, “EU long-term dataset with multiple sensors for autonomous driving,” in Proceedings of the 2020 IEEE/RSJ International Conference on Intelligent Robots and Systems (IROS), 2020.7

**Comment by xingyuuchen** [comment]
Hello @grdiv ,

Thanks for your interest!

I just tried the official channel, i.e. [https://epan-utbm.github.io/utbm_robocar_dataset/](https://epan-utbm.github.io/utbm_robocar_dataset/), it seems there is no problem to download?

**Comment by grdiv** [comment]
OK.

> Hello @grdiv ,
> 
> Thanks for your interest!
> 
> I just tried the official channel, i.e. https://epan-utbm.github.io/utbm_robocar_dataset/, it seems there is no problem to download?
