### ISSUE TITLE
fast & faster lio  with PPF

### ISSUE THREAD

**Issue by wolf943134497** [xingyuuchen/LIO-PPF#4]
Hi  @xingyuuchen  Thanks for your great works and released code.
I see  from your paper that you applied PPF to fast & faster lio， and achieved good results. fast & faster lio is more efficient than lio sam.
could you release the code of fast & faster lio  with PPF. Thanks a lot.

**Comment by xingyuuchen** [comment]
Sure, but I am busy with other things these days.
I'll upload those codes later.

Btw, you can transfer the related code into Fastlio2 yourself. It's not too hard.😽

**Comment by robot-mh** [comment]
> Sure, but I am busy with other things these days. I'll upload those codes later.
> 
> Btw, you can transfer the related code into Fastlio2 yourself. It's not too hard.😽

how about now？

**Comment by xingyuuchen** [comment]
> > Sure, but I am busy with other things these days. I'll upload those codes later.
> 
> > 
> 
> > Btw, you can transfer the related code into Fastlio2 yourself. It's not too hard.😽
> 
> 
> 
> how about now？

These two days may be OK！

**Comment by xingyuuchen** [comment]
> > Sure, but I am busy with other things these days. I'll upload those codes later.
> > Btw, you can transfer the related code into Fastlio2 yourself. It's not too hard.😽
> 
> how about now？

Faster-LIO with PPF is now available in this repo: [faster-lio-ppf](https://github.com/xingyuuchen/faster-lio-ppf).

Thanks for waiting so looooong!!!

(Btw, I should have published them much earlier. Just because I've been busy with my graduation thesis so I didn't. Sorry for the inconvenience!!)

**Comment by xingyuuchen** [comment]
> Hi @xingyuuchen Thanks for your great works and released code. I see from your paper that you applied PPF to fast & faster lio， and achieved good results. fast & faster lio is more efficient than lio sam. could you release the code of fast & faster lio with PPF. Thanks a lot.

Hello @wolf943134497 ,

Faster-LIO with PPF is now available in this repo: [faster-lio-ppf](https://github.com/xingyuuchen/faster-lio-ppf).

Thanks for waiting so looooong!!!

(Btw, I should have published them much earlier. Just because I've been busy with my graduation thesis so I didn't. Sorry for the inconvenience!!)

Best,
Xingyu

**Comment by xingyuuchen** [comment]
I'm closing this issue, feel free to reopen it with any questions!
