### ISSUE TITLE
依赖glog

### ISSUE THREAD

**Issue by HIT-Ygq** [xingyuuchen/LIO-PPF#5]
![e2](https://github.com/xingyuuchen/LIO-PPF/assets/90457565/817f21b3-5af1-4924-a44e-95e118532a8c)
编译过程中，出现了以下错误，但我重新下载glog,gflags,还是没有解决，你遇到过这样的问题嘛

**Comment by xingyuuchen** [comment]
你好，这应该是cmake没找到你的glog，更具体一点是链接器没链接到libglog.so。可以看看那几个跟glog有关的cmake变量（Glog_LIBRARY等）是否被设置正确？
