### ISSUE TITLE
Kitti data

### ISSUE THREAD

**Issue by dkjsednfkjsn** [xingyuuchen/LIO-PPF#7]
Hello author, thank you for your work, can you provide the configuration file for running on the kitti data set?

**Comment by xingyuuchen** [comment]
Hello @dkjsednfkjsn ,

It is the same as that from LIO-SAM~

**Comment by dkjsednfkjsn** [comment]
> Hello @dkjsednfkjsn ,
> 
> It is the same as that from LIO-SAM~

Thank you for your reply. I have encountered some problems at present. I would like to refer to your parameters that are different from liosam. Is it convenient for you to publish them?

**Comment by xingyuuchen** [comment]
> > Hello @dkjsednfkjsn ,
> > It is the same as that from LIO-SAM~
> 
> Thank you for your reply. I have encountered some problems at present. I would like to refer to your parameters that are different from liosam. Is it convenient for you to publish them?

Sure, no problem. I just checked my laptop computer with me and found the file you needed is in the desktop computer in my Lab. I'll go back to Lab and publish all of those in 21st Mar.

(Btw, I should have published them much earlier. Just because I've been busy with my graduation thesis so I didn't. Sorry for the inconvenience!!)

**Comment by dkjsednfkjsn** [comment]
> > > Hello @dkjsednfkjsn ,
> > > It is the same as that from LIO-SAM~
> > 
> > 
> > Thank you for your reply. I have encountered some problems at present. I would like to refer to your parameters that are different from liosam. Is it convenient for you to publish them?
> 
> Sure, no problem. I just checked my laptop computer with me and found the file you needed is in the desktop computer in my Lab. I'll go back to Lab and publish all of those in 21st Mar.
> 
> (Btw, I should have published them much earlier. Just because I've been busy with my graduation thesis so I didn't. Sorry for the inconvenience!!)

Thank you so much for your reply and excellent work, and good luck with your graduation!

**Comment by xingyuuchen** [comment]
Hello @dkjsednfkjsn ,

Your required files are committed. See [here](https://github.com/xingyuuchen/LIO-PPF/commit/bfcb45c66a4e983991e10f66fb5d2996d28d6d5d).


Commands to run:
`roslaunch lio_sam kitti.launch`

In another terminal, run:
`rosbag play /path/to/your/kittibagfile/2011_xx_xx_drive_00xx.bag`

**Comment by xingyuuchen** [comment]
I'm closing this issue, feel free to open it again if you have any new questions!

**Comment by xingyuuchen** [comment]
I'm closing this issue, feel free to open it again if you have any new questions!
