### ISSUE TITLE
does LIO-PPF work with 6-dof IMU?

### ISSUE THREAD

**Issue by NamDinhRobotics** [xingyuuchen/LIO-PPF#8]
Thank you for your great source.
I want to use livox MID_360, could it work with 6-DOF IMU?

Bests,

**Comment by xingyuuchen** [comment]
Hi @NamDinhRobotics ,

Thanks for your interests in our work!
As for now, LIO-PPF works under the condition of what `LIO-SAM` or `Faster-LIO2` works under.
IIRC, these two only support 3-DoF IMU? Sorry I cant really recall the exact answer as this work was done more than 2 years ago 😹.
